controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_register:
    path: /api/register
    controller: App\Controller\RegisterController::register
    methods: [POST]

# config/routes.yaml
api_login_check:
    path: /api/login_check

app_profile:
    path: /api/profile
    controller: App\Controller\ProfileController::profile
    methods: [GET]

app_file:
    path: /api/files
    controller: App\Controller\FileController::getAllFiles
    methods: [GET]

app_file_detail:
    path: /api/file/{id}
    controller: App\Controller\FileController::getFileById
    methods: [GET]

api_file_delete:
    path: /api/file/delete/{id}
    controller: App\Controller\FileController::deleteFile
    methods: [DELETE]