controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_register:
    path: /api/register
    controller: App\Controller\RegisterController::register
    methods: [POST]

# config/routes.yaml
api_login_check:
    path: /api/login_check

app_profile:
    path: /api/profile
    controller: App\Controller\ProfileController::profile
    methods: [GET]

app_category:
    path: /api/category
    controller: App\Controller\CategoryController::getAllCategories
    methods: [GET]

api_search_file:
    path: /api/file/search_file
    controller: App\Controller\FileController::searchFile
    methods: [GET]

app_file:
    path: /api/files
    controller: App\Controller\FileController::getAllFiles
    methods: [GET]

app_file_detail:
    path: /api/file/{id}
    controller: App\Controller\FileController::getFileById
    methods: [GET]

app_file_update:
    path: /api/file/update_file/{id}
    controller: App\Controller\FileController::createOrUpdate
    methods: [POST]

app_file_delete:
    path: /api/file/delete/{id}
    controller: App\Controller\FileController::deleteFile
    methods: [DELETE]

app_client_file:
    path: /api/client/files/{id}
    controller: App\Controller\ClientController::getFilesOfClient
    methods: [GET]

app_client_file_details:
    path: /api/client/file/{id}
    controller: App\Controller\ClientController::getFileOfClientById
    methods: [GET]

app_client_file_download:
    path: /api/client/file/download/{id}
    controller: App\Controller\ClientController::downloadFile
    methods: [GET]

app_file_create:
    path: /api/file/create_file
    controller: App\Controller\FileController::createOrUpdate
    methods: [POST]

app_client:
    path: /api/client
    controller: App\Controller\ClientController::getAllClients
    methods: [GET]

app_client_statistics:
    path: /api/client/statistics
    controller: App\Controller\ClientController::getStatistics
    methods: [GET]

api_file_search:
    path: /api/client/search_file
    controller: App\Controller\ClientController::searchFile
    methods: [GET]
