export const countries = [
    'Allemagne',
    'Andorre',
    'Angleterre',
    'Autriche',
    'Belgique',
    'Biélorussie',
    'Bosnie-Herzégovine',
    'Bulgarie',
    'Chine',
    'Chypre',
    'Croatie',
    'Danemark',
    'Écosse',
    'Espagne',
    'Estonie',
    'États-Unis',
    'Finlande',
    'France',
    'Grèce',
    'Hongrie',
    'Irlande',
    'Irlande du Nord',
    'Islande',
    'Italie',
    'Kosovo',
    'Lettonie',
    'Liechtenstein',
    'Lituanie',
    'Luxembourg',
    'Macédoine du Nord',
    'Malte',
    'Moldavie',
    'Monaco',
    'Monténégro',
    'Norvège',
    'Pays-Bas',
    'Pays de Galles',
    'Pologne',
    'Portugal',
    'République Tchèque',
    'Roumanie',
    'Royaume-Uni',
    'Russie',
    'Saint-Marin',
    'Serbie',
    'Slovaquie',
    'Slovénie',
    'Suède',
    'Suisse',
    'Ukraine',
    'Vatican',
]
